name = "Quint"
license = "MIT"
licenselink = "https://github.com/victoriadrake/hugo-theme-quint/blob/master/LICENSE"
description = "Quint: Essence of Minimalism."
homepage = "https://github.com/victoriadrake/hugo-theme-quint"
tags = ["responsive","minimal","light","dark","personal","dark mode"]
features = []
min_version = "0.125.4"

[author]
  name = "Victoria Drake"
  homepage = "https://victoria.dev"
